### ISSUE TITLE
Update Gentoo's Page With Link To This Project

### ISSUE THREAD

**Issue by jlpoolen** [packergundo/gentoo-pi#1]
Gentoo's https://wiki.gentoo.org/wiki/Raspberry_Pi has a link:

[gentoo-pi ](http://www.gundo.com/gentoo-pi)maintained base headless Gentoo image, with distcc and sshd enabled.

and the page linked to at gundo.com looks stale when compared to this project.  I recommend you consider updating Gentoo's page (or request and update) so that people interested in this subject are directed to your current area.

Cheers

**Comment by packergundo** [comment]
This has been fixed on the Gentoo wiki
